# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('ad_client_id', 'AD Client ID'), ('ad_org_id', 'AD Org ID'), ('ad_role_id', 'AD Role ID'), ('m_warehouse_id', 'M Warehouse ID'), ('user', 'Username'), ('pass', 'Password')], max_length=40, unique=True, verbose_name='Name')),
                ('value', models.CharField(max_length=40, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'EBatch Config',
            },
        ),
    ]
