# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20161201_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchproc',
            name='state',
            field=models.CharField(choices=[('DR', 'New'), ('CO', 'Complete'), ('UP', 'Upload')], default='DR', max_length=2, verbose_name='State'),
        ),
    ]
