# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20161201_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchproc',
            name='c_batch_plant_id',
            field=models.CharField(max_length=100, null=True, verbose_name='BatchID'),
        ),
    ]
