# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_batchproc_c_batch_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchconfig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchconfig',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchproc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchproc',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
