# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_auto_20161202_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchconfig',
            name='name',
            field=models.CharField(choices=[('ad_url', 'ADempiere URL'), ('ad_client_id', 'AD Client ID'), ('ad_org_id', 'AD Org ID'), ('ad_role_id', 'AD Role ID'), ('m_warehouse_id', 'M Warehouse ID'), ('username', 'Username'), ('password', 'Password'), ('mssql_host', 'MSSQL Host'), ('mssql_port', 'MSSQL Port'), ('mssql_db', 'MSSQL Database'), ('mssql_user', 'MSSQL Username'), ('mssql_pass', 'MSSQL Password')], max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='batchproc',
            name='batch_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='BatchID'),
        ),
    ]
