# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_auto_20161202_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadProc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='LoadID')),
                ('c_batch_plant_id', models.CharField(max_length=100, null=True, verbose_name='Forca LoadID')),
                ('batch_created', models.DateTimeField(verbose_name='CreatedDate')),
                ('state', models.CharField(choices=[('DR', 'New'), ('CO', 'Complete'), ('UP', 'Upload')], default='DR', max_length=2, verbose_name='State')),
            ],
            options={
                'verbose_name': 'EBatch Ticket Proc',
            },
        ),
        migrations.CreateModel(
            name='TicketProc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='TicketID')),
                ('c_batch_plant_id', models.CharField(max_length=100, null=True, verbose_name='Forca TicketID')),
                ('batch_created', models.DateTimeField(verbose_name='CreatedDate')),
                ('state', models.CharField(choices=[('DR', 'New'), ('CO', 'Complete'), ('UP', 'Upload')], default='DR', max_length=2, verbose_name='State')),
            ],
            options={
                'verbose_name': 'EBatch Ticket Proc',
            },
        ),
        migrations.DeleteModel(
            name='BatchProc',
        ),
    ]
