# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20161225_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='BatchID')),
                ('c_batch_plant_id', models.CharField(max_length=100, null=True, verbose_name='BatchID')),
                ('batch_created', models.DateTimeField(verbose_name='CreatedDate')),
                ('state', models.CharField(choices=[('DR', 'New'), ('CO', 'Complete'), ('UP', 'Upload')], default='DR', max_length=2, verbose_name='State')),
            ],
            options={
                'verbose_name': 'EBatch Batch Proc',
            },
        ),
    ]
