# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_batchproc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadproc',
            options={'verbose_name': 'EBatch Load Proc'},
        ),
        migrations.RenameField(
            model_name='batchproc',
            old_name='c_batch_plant_id',
            new_name='c_batch_id',
        ),
        migrations.RenameField(
            model_name='loadproc',
            old_name='c_batch_plant_id',
            new_name='c_load_id',
        ),
        migrations.RenameField(
            model_name='loadproc',
            old_name='batch_created',
            new_name='load_created',
        ),
        migrations.RenameField(
            model_name='loadproc',
            old_name='batch_id',
            new_name='load_id',
        ),
        migrations.RenameField(
            model_name='ticketproc',
            old_name='c_batch_plant_id',
            new_name='c_ticket_id',
        ),
        migrations.RenameField(
            model_name='ticketproc',
            old_name='batch_created',
            new_name='ticket_created',
        ),
        migrations.RenameField(
            model_name='ticketproc',
            old_name='batch_id',
            new_name='ticket_id',
        ),
    ]
