# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0017_auto_20161225_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadProc',
        ),
    ]
