# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_loadproc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLineProc',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('loadline_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Load_LineID')),
                ('c_loadline_id', models.CharField(max_length=100, null=True, verbose_name='Forca Load_LineID')),
                ('state', models.CharField(choices=[('DR', 'New'), ('CO', 'Complete'), ('UP', 'Upload')], default='DR', max_length=2, verbose_name='State')),
                ('load_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.LoadProc')),
            ],
            options={
                'verbose_name': 'EBatch LoadLine Proc',
            },
        ),
    ]
