# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_loadlineproc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadlineproc',
            name='c_loadline_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forca Load_LineID'),
        ),
        migrations.AlterField(
            model_name='loadproc',
            name='c_load_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forca LoadID'),
        ),
    ]
